#!/usr/bin/bash
#
# demo use of memory file (that lives in RAM), created with memfd_create.c

# read memory file name
read -r pid mfd < <(./memfd_create &)

# show name
mf=/proc/$pid/fd/$mfd
echo "$mf"

# fill memory file
echo foo > "$mf"
echo bar >> "$mf"

# output memory file
cat "$mf"

# terminate memfd_create.c by its pid, in order to close memory file
kill "$pid"

# memory file does not exist anymore after memfd_create.c ended
cat "$mf"
