#!/usr/bin/bash

# read memory file name
read -r pid mfd < <(./memfd_create &)

# create 10MB ext2 filesystem in memory file
mnt=/proc/$pid/fd
mf=$mnt/$mfd
dd if=/dev/zero of="$mf" bs=1024 count=10240 2> /dev/null
mkfs.ext2 "$mf" 2>&1 | cat > /dev/null 

# mount that filesystem, and switch ownership to pi user
sudo mount "$mf" "$mnt"
sudo chown pi. "$mnt"

# show name of mounted filesystem
echo "$mnt"

# create new file
echo "foo" > "$mnt/bar"

# show directory
ls -l "$mnt"

# show created file
cat "$mnt/bar"

# terminate memfd_create.c by its pid, in order to close memory file
kill "$pid"
